### list
GET http://localhost:9129/list?app=app1&env=dev&ns=public

### update Configs
POST http://localhost:9129/update?app=app1&env=dev&ns=public&pkey=kk.a
content-type: application/json

{
"my.a": "updated2"
}
