server:
  port: 9129

spring:
  application:
    name: myconfig-server
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:h2db
    username: root
    password: 123456
  sql:
    init:
      platform: h2
      schema-locations: classpath:/init.sql
      #      data-locations: classpath:/data.sql
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl